### ISSUE TITLE
TD3+BC

### ISSUE THREAD

**Issue by LuggiStruggi** [hufflepuff79/online_stagnation_teaching#2]
Implement [TD3+BC](https://arxiv.org/pdf/2106.06860.pdf) with the [unplugged-rl](https://github.com/deepmind/deepmind-research/tree/master/rl_unplugged) dataset. For this get a MuJoCo student license, but use the free trial until it gets validated.
This has already been implemented in pytorch for the D4RL dataset [here](https://github.com/sfujim/TD3_BC).
This will be trained on our home machines.

**Comment by hufflepuff79** [comment]
Starting on implementing the network architectures. Please use branch TD3+BC to collaboratively implement  :)
